## docker build -t fair-frontend:latest .
## docker run --rm --name fair-frontend-temp fair-frontend:latest

# Build stage
FROM node:22 AS builder
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm
RUN pnpm install --force
COPY . .
RUN pnpm run build

# Export stage
FROM alpine:latest AS exporter
WORKDIR /app
COPY --from=builder /app/dist ./dist
