version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_CPU
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      EXPORT_TOOL_API_URL: ${EXPORT_TOOL_API_URL}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      OSM_CLIENT_ID: ${OSM_CLIENT_ID}
      OSM_CLIENT_SECRET: ${OSM_CLIENT_SECRET}
      OSM_URL: ${OSM_URL}
      OSM_SCOPE: ${OSM_SCOPE}
      OSM_LOGIN_REDIRECT_URI: ${OSM_LOGIN_REDIRECT_URI}
      OSM_SECRET_KEY: ${OSM_SECRET_KEY}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      RAMP_HOME: ${RAMP_HOME}
      TRAINING_WORKSPACE: ${TRAINING_WORKSPACE}
      TESTING_TOKEN: ${TESTING_TOKEN}
      GDAL_LIBRARY_PATH: ${GDAL_LIBRARY_PATH}
      MAXAR_CONNECT_ID: ${MAXAR_CONNECT_ID}
      FRONTEND_URL: ${FRONTEND_URL}
      BUCKET_NAME: ${BUCKET_NAME}
      PARENT_BUCKET_FOLDER: ${PARENT_BUCKET_FOLDER}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      PRESIGNED_URL_EXPIRY: ${PRESIGNED_URL_EXPIRY}
      EPOCHS_LIMIT: ${EPOCHS_LIMIT}
      BATCH_SIZE_LIMIT: ${BATCH_SIZE_LIMIT}
      YOLO_EPOCHS_LIMIT: ${YOLO_EPOCHS_LIMIT}
      YOLO_BATCH_SIZE_LIMIT: ${YOLO_BATCH_SIZE_LIMIT}
      RAMP_EPOCHS_LIMIT: ${RAMP_EPOCHS_LIMIT}
      RAMP_BATCH_SIZE_LIMIT: ${RAMP_BATCH_SIZE_LIMIT}
      TRAINING_WORKSPACE_DOWNLOAD_LIMIT: ${TRAINING_WORKSPACE_DOWNLOAD_LIMIT}
      DEFAULT_PAGINATION_SIZE: ${DEFAULT_PAGINATION_SIZE}
      CORS_ORIGIN_ALLOW_ALL: ${CORS_ORIGIN_ALLOW_ALL}
      ENABLE_PREDICTION_API: ${ENABLE_PREDICTION_API}
      LOG_LINE_STREAM_TRUNCATE_VALUE: ${LOG_LINE_STREAM_TRUNCATE_VALUE}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_USE_SSL: ${EMAIL_USE_SSL}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  pgsql:
    image: "postgis/postgis"
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
